using System.Text;

namespace TitanEndpoint.Core.Config;

/// <summary>
/// Produces the one runtime source map consumed by both the native Correlator and the
/// Custom Rule titan_sensors collector. It is generated from the already manifest-overlaid
/// EndpointDefinition values, eliminating historical Debug/final-audit paths.
/// </summary>
public static class RuntimeConfiguration
{
    private static readonly (EndpointId Id, string SourceName)[] SensorSources =
    {
        (EndpointId.Port, "port"),
        (EndpointId.Process, "process"),
        (EndpointId.File, "file_integrity"),
        (EndpointId.Network, "network"),
        (EndpointId.Application, "application")
    };

    public static string Prepare(TitanSettings settings)
    {
        ArgumentNullException.ThrowIfNull(settings);
        var root = settings.TitanRootDirectory;
        if (string.IsNullOrWhiteSpace(root))
            throw new InvalidOperationException("TITAN root directory is not configured.");

        var runtimeDirectory = Path.Combine(root, ".titan-runtime");
        Directory.CreateDirectory(runtimeDirectory);
        var configPath = Path.Combine(runtimeDirectory, "correlator_config.txt");

        var lines = new List<string>
        {
            "# Generated by TITAN GUI from runtime-manifest.json. Do not edit while TITAN is running.",
            $"# generated_utc={DateTimeOffset.UtcNow:O}"
        };
        foreach (var (id, sourceName) in SensorSources)
        {
            var definition = settings.GetEndpoint(id);
            if (string.IsNullOrWhiteSpace(definition.LogDirectory))
                throw new InvalidOperationException($"{definition.DisplayName} has no log directory configured.");
            lines.Add($"{sourceName}={Path.GetFullPath(definition.LogDirectory)}");
        }

        WriteAtomic(configPath, string.Join(Environment.NewLine, lines) + Environment.NewLine);
        settings.RuntimeCorrelatorConfigPath = configPath;

        var correlator = settings.GetEndpoint(EndpointId.Correlator);
        correlator.RuntimeCommandArguments = Quote(configPath);
        return configPath;
    }

    private static string Quote(string value) => $"\"{value.Replace("\"", "\\\"")}\"";

    private static void WriteAtomic(string path, string content)
    {
        var temporary = path + ".tmp";
        using (var stream = new FileStream(temporary, FileMode.Create, FileAccess.Write,
                   FileShare.None, 16 * 1024, FileOptions.WriteThrough))
        using (var writer = new StreamWriter(stream, new UTF8Encoding(false)))
        {
            writer.Write(content);
            writer.Flush();
            stream.Flush(flushToDisk: true);
        }
        File.Move(temporary, path, overwrite: true);
    }
}
